apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kubepoc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubepoc-pod
  template:
    metadata:
      labels:
        app: kubepoc-pod
    spec:
      containers:
      - name: kubepoc
        image: getkubepoc:1
        imagePullPolicy: Never


